import type { Metadata } from 'next';
import StyledComponentsRegistry from './registry';
import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <StyledComponentsRegistry>
          <body>{children}</body>
        </StyledComponentsRegistry>
      </StoreProvider>
    </html>
  );
}
